{
 "title": "H10",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT tstamp as \"time\", concat('cpu_id: ', cpu_id), temp as \" \"\nFROM h10_logs"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT tstamp as \"time\", concat('cpu_id: ', cpu_id), hum as \" \"\nFROM h10_logs"
    }
   ]
  },
  {
   "title": "VCC",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "rawSql": "SELECT tstamp as \"time\", concat('cpu_id: ', cpu_id), vcc as \" \"\nFROM h10_logs"
    }
   ]
  },
  {
   "title": "VPANEL",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "rawSql": "SELECT tstamp as \"time\", concat('cpu_id: ', cpu_id), vpanel as \" \"\nFROM h10_logs"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT tstamp as \"time\", concat('cpu_id: ', cpu_id), rssi as \" \"\nFROM h10_logs"
    }
   ]
  },
  {
   "title": "SNR",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT tstamp as \"time\", concat('cpu_id: ', cpu_id), snr as \" \"\nFROM h10_logs"
    }
   ]
  }
 ]
}